site_name: Class Notes

theme:
  name: 'material'

  features:
    - navigation.tabs
    - search.suggest
    - search.share

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: material/console-network

  palette:
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

extra_css:
  - stylesheets/style.css
  - stylesheets/chemistry.min.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - mkdocs-click

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home:
    - Home: index.md
    - cli.md
  - English:
    - Home: 'EL5131/index.md'
    - 'EL5131/Stats and Quotes Notes.md'
    - Technology:
      - Big Tech:
        - Home: 'EL5131\Technology\Big Tech\index.md.md'
        - Articles:
          - 'EL5131/Technology/Big Tech/Articles/article0.md'
          - 'EL5131/Technology/Big Tech/Articles/article1.md'
        - Essays:
          - 'EL5131\Technology\Big Tech\Essays\essay0.md'
          - 'EL5131\Technology\Big Tech\Essays\essay1.md'
      - Cancel Culture:
        - Essays:
          - 'EL5131\Technology\Cancel Culture\Essays\essay0.md'
    - Unit 1 - 4th Industrial Revolution:
      - 'EL5131/FourIR/Industry.md'
      - Articles:
        - 'EL5131/FourIR/Articles/article0.md'
        - 'EL5131/FourIR/Articles/article1.md'
    - Unit 2 - Climate Change:
      - Home: 'EL5131/Climate Change/index.md'
      - 'EL5131/Climate Change/Singapore.md'
      - 'EL5131/Climate Change/Global Efforts.md'
      - 'EL5131/Climate Change/Worldwide Impact.md'
      - Articles:
        - 'EL5131\Climate Change\Articles\article0.md'
        - 'EL5131\Climate Change\Articles\article1.md'
        - 'EL5131\Climate Change\Articles\article2.md'
        - 'EL5131\Climate Change\Articles\article3.md'
        - 'EL5131\Climate Change\Articles\article4.md'
    - Unit 2 - Pandemic:
      - 'EL5131/Pandemic/Pandemic.md'
      - Articles:
        - 'EL5131\Pandemic\Articles\article0.md'
  - PC5131:
    - Home: 'PC5131/index.md'
    - 'PC5131/Rotational Mechanics.md'
    - 'PC5131/Waves I.md'
    - 'PC5131/Physical Optics.md'
    - 'PC5131/Geometric Optics.md'
  - CM5131:
    - Home: 'CM5131/index.md'
    - 'CM5131/Intro to Organic Chem.md'
    - 'CM5131/Alkanes.md'
    - 'CM5131/Alkenes.md'
  - CS5131:
    - Knowledge:
      - Logic Classes: 'CS5131/Knowledge/logic.py'
      - Harry Potter Conundrum: 'CS5131/Knowledge/harry.py'
      - Mastermind via Logic: 'CS5131/Knowledge/mastermind.py'
      - Puzzle via Logic: 'CS5131/Knowledge/puzzle.py'
  - MA5431:
      - Chapter 4 - Eigenvalues and Eigenvectors: 'MA5431/chapter4.md'

plugins:
  - mkdocs-jupyter
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/M22504

copyright: Copyright &copy; 2022 M22504
