site_name: Class Notes

theme:
  name: 'material'

  features:
    - navigation.tabs

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: material/telescope

  palette:
    - scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - English:
    - Home: 'EL5131/index.md'
    - 'EL5131/Stats and Quotes Notes.md'
    - Technology:
      - Big Tech:
        - Home: 'EL5131\Technology\Big Tech\index.md.md'
        - Articles:
          - 'EL5131/Technology/Big Tech/Articles/article0.md'
          - 'EL5131/Technology/Big Tech/Articles/article1.md'
        - Essays:
          - 'EL5131\Technology\Big Tech\Essays\essay0.md'
          - 'EL5131\Technology\Big Tech\Essays\essay1.md'
      - Cancel Culture:
        - Essays:
          - 'EL5131\Technology\Cancel Culture\Essays\essay0.md'
    - Unit 1 - 4th Industrial Revolution:
      - Articles:
        - 'EL5131/FourIR/Articles/article0.md'
        - 'EL5131/FourIR/Articles/article1.md'
    - Unit 2 - Climate Change:
      - 'EL5131/Climate Change/Singapore.md'
      - 'EL5131/Climate Change/Global Efforts.md'
      - 'EL5131/Climate Change/Worldwide Impact.md'
      - Articles:
        - 'EL5131/Climate Change/Net Zero is Not Zero.md'
  - PC5131:
    - Home: 'PC5131/index.md'
    - 'PC5131/Rotational Mechanics.md'
    - 'PC5131/Waves I.md'
